### ISSUE TITLE
newline between parameters of imported parametrized attribute set

### ISSUE THREAD

**Issue by timhae** [serokell/nixfmt#83] opened 2021-12-27 18:01 UTC
### Description

Thanks for your helpful tool! I have one minor issue when formatting the example input

### Small example input

```
{ addressPrefix ? "", host ? "", address ? "${addressPrefix}@${host}"
, userName ? address, imapHost ? "${host}", smtpHost ? "${host}", realName
, posteoKey ? "", gmailKey ? "", key ? "${posteoKey}${gmailKey}"
, signByDefault ? (if key == "" then false else true)
, passName ? "${host}/${address}", mbsyncExtra ? { }, primary ? false }: {
  inherit address realName primary userName;
  imap.host = imapHost;
  smtp.host = smtpHost;
  passwordCommand = "pass show ${passName}";
  gpg = { inherit key signByDefault; };
  mbsync = {
    enable = true;
    create = "maildir";
    extraConfig.account = mbsyncExtra;
  };
  neomutt.enable = true;
  msmtp.enable = true;
  notmuch.enable = true;
}
```

this is what I use to include multiple mail accounts with similar settings into my home manager [configuration](https://github.com/timhae/nixconfig/blob/main/common/commonHome.nix#L50). Instead of the current output which is identical to the example input, I would prefer something like in the expected output.

### Expected output

```
{ addressPrefix ? ""
, host ? ""
, address ? "${addressPrefix}@${host}"
, userName ? address
, imapHost ? "${host}"
, smtpHost ? "${host}"
, realName
, posteoKey ? ""
, gmailKey ? ""
, key ? "${posteoKey}${gmailKey}"
, signByDefault ? (if key == "" then false else true)
, passName ? "${host}/${address}"
, mbsyncExtra ? { }
, primary ? false }:
{
  inherit address realName primary userName;
  imap.host = imapHost;
  smtp.host = smtpHost;
  passwordCommand = "pass show ${passName}";
  gpg = { inherit key signByDefault; };
  mbsync = {
    enable = true;
    create = "maildir";
    extraConfig.account = mbsyncExtra;
  };
  neomutt.enable = true;
  msmtp.enable = true;
  notmuch.enable = true;
}
```
please let me know what you think of this idea.

**Comment by yorickvP** [comment] 2022-02-25 14:27
Thanks for your report! This is definitely on the todo list. Closing this because it's a duplicate of #46. Please reopen if not.

**Closed by yorickvP** 2022-02-25 14:27 UTC
Labels: duplicate, enhancement, help wanted
