### ISSUE TITLE
Some parser/formatter problems

### ISSUE THREAD

**Issue by Infinisil** [serokell/nixfmt#2] opened 2019-05-12 18:36 UTC
Nice project btw! Gonna highlight some things I've noticed that could be problematic.

```nix
let {
  body = true;
}
```
Doesn't parse. This syntax isn't used often, but it is part of Nix.

---

```nix
"hello
there"
```
Gets transformed to
```nix
''
  hello
  there''
```
which is odd.

---

```nix
"\r"
```
Which evaluates to `"\r"` with `nix-instantiate --eval`

gets transformed into
```nix
"^M"
```
(where ^M is an actual carriage return)
Which evaluates to `"\n"`.

---

In general, I think it's important for a formatter to preserve what the expression evaluates to, but considering the string-madness Nix has, I'm not sure how feasible this is. Take a look at [this Nix test](https://github.com/NixOS/nix/blob/master/tests/lang/eval-okay-ind-string.nix) for example. All of Nix's tests might be good tests for this formatter.

**Comment by kirelagin** [comment] 2019-05-12 23:47
> ```nix
> let {
>  body = true;
> }
> ```

Wow, omg, I’ve been using Nix for quite some time and I had no idea! I couldn’t find anything about it in the docs... not a single use in Nixpkgs... but now after searching GitHub I see that people actually do use this syntax! Thanks for bringing this up.

**Comment by yorickvP** [comment] 2019-05-13 14:49
Note that
```nix
let body = true; in
let { inherit body; }
```
also works.

**Comment by Lucus16** [comment] 2019-05-13 17:17
Regarding multiline strings, for consistency I've chosen to throw away the type of strings and then use some simple heuristics to determine what type fits best. I think in your example, `"hello\nthere"` might be an acceptable rendering, although it is hard to determine at what point a string should be rendered as an indented string. The input you gave is certainly not acceptable because the second line cannot be indented. It's possible to introduce an extra newline at the end to render it as a normal indented string, but this would change the semantics and can break code.

The other two issues are things I intend to fix. I didn't know about this form of `let` syntax. In the future, please create separate issues, discussing three unrelated issues in a single thread is rather unwieldy.

**Comment by Lucus16** [comment] 2019-05-15 15:45
Apparently, `"^M" == "\n"` and `''^M'' == "\r"`. I'm going to report this to Nix and see if they think this is a bug or intended behavior.

**Comment by kirelagin** [comment] 2019-05-22 16:36
https://github.com/NixOS/nix/issues/2811

**Comment by Lucus16** [comment] 2019-05-23 20:30
I'm going to just convert `^M` to `\r` in simple strings regardless, it's probably clearer that way anyway.

**Comment by Lucus16** [comment] 2019-05-23 20:30
Both issues now fixed in master.

**Closed by Lucus16** 2019-05-23 20:30 UTC
